# Generated by Django 4.2.8 on 2023-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("age", models.IntegerField()),
                ("position", models.TextField()),
                ("desc", models.CharField(max_length=500)),
                ("market_value", models.IntegerField()),
            ],
        ),
    ]
