# Generated by Django 4.2.8 on 2023-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="img",
            field=models.ImageField(default="hai", upload_to="pics"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="players", name="desc", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="players", name="name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="players",
            name="position",
            field=models.CharField(max_length=50),
        ),
    ]
