# Generated by Django 4.2.7 on 2023-11-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="newspic")),
                ("desc", models.TextField()),
            ],
        ),
    ]
