# Generated by Django 4.2.8 on 2023-12-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="img",
            field=models.ImageField(default="ggs", upload_to="gallery"),
            preserve_default=False,
        ),
    ]
